version: '3'
services:
  tp-foyer:
    image: devops4040/tp-foyer:5.0.0
    ports:
      - "8089:8089"
    networks:
      - app-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge